---
# Configure network for SLURM cluster

- name: Generate /etc/hosts file from inventory
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  

- name: Ensure hostname resolution works
  ansible.builtin.command: hostname -f
  register: hostname_result
  changed_when: false

- name: Display hostname resolution result
  ansible.builtin.debug:
    var: hostname_result.stdout
