---
# Install common packages required for SLURM cluster

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    cache_valid_time: 3600

- name: Install common packages for Debian/Ubuntu
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - chrony
    state: present
