---
# Install common packages required for SLURM cluster

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    cache_valid_time: 3600
  become: true

- name: Install common packages for Debian/Ubuntu
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - ntp
      - nfs-common
      - munge
      - libmunge-dev
      - python3
      - python3-pip
      #- environment-modules
      #- libibverbs-dev
      #- librdmacm-dev
      #- openmpi-bin
      #- openmpi-common
      #- libopenmpi-dev
    state: present
  become: true
