---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    cache_valid_time: 3600
  register: apt_update

- name: Install common packages
  ansible.builtin.apt:
    name:
      - build-essential
      - chrony
      - git
    state: present
  register: package_install

- name: Reboot the server if needed
  ansible.builtin.reboot:
    reboot_timeout: 600         # 10 minutes
    pre_reboot_delay: 30        # 30 seconds
    post_reboot_delay: 30       # 30 seconds
    test_command: whoami        # Command to verify system is back up
    msg: "Rebooting by Ansible after upgrade" # Message to display to users
  when: apt_update.changed or package_install.changed
