---
- name: Set timezone to Europe/Berlin
  ansible.builtin.timezone:
    name: Europe/Berlin

- name: Configure chrony server
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: '0644'
  notify: Restart chronyd

- name: Enable and start chronyd service
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
