---
# Equivalent to step-1-install-gpu-driver.sh in cGPU onboarding package (r570 nvidia driver)
- name: Install build dependencies
  ansible.builtin.apt:
    name:
      - gcc
      - g++
      - make
      - python3-dev
    state: present
    install_recommends: true
    dpkg_options: 'force-confdef,force-confold'
    lock_timeout: 300

- name: Install NVIDIA drivers
  ansible.builtin.apt:
    name:
      - nvidia-driver-570-server-open
      - linux-modules-nvidia-570-server-open-azure
    state: present
    install_recommends: true
    dpkg_options: 'force-confdef,force-confold'
    lock_timeout: 300

- name: Enable NVIDIA persistence mode
  ansible.builtin.command: nvidia-smi -pm 1
  changed_when: false

- name: Create rc.local script for NVIDIA persistence
  ansible.builtin.copy:
    dest: /etc/rc.local
    content: |
      #!/bin/bash
      nvidia-smi -pm 1
      nvidia-smi conf-compute -srs 1
    mode: '0755'
  notify: Reboot
