---
# Main tasks file for the gpu role

- name: Include GPU tasks for tee_off nodes
  ansible.builtin.import_tasks: gpu-tee-off.yaml
  when: inventory_hostname in groups['tee_off']

- name: Include GPU tasks for tee_on nodes
  ansible.builtin.import_tasks: gpu-tee-on.yaml
  when: inventory_hostname in groups['tee_on']
