---
# Main tasks file for the gpu role

- name: Include GPU tasks for tee_on nodes
  ansible.builtin.import_tasks: gpu.yaml
  when: inventory_hostname in groups['tee_on'] # TODO also check that we use the gpu tfvars
