---
- name: Create shared directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /shared
    - /shared/home
    - /shared/apps
    - /shared/data
  become: true
  when: inventory_hostname in groups['control'] 
