---
# Handlers for slurm

- name: Restart munge
  ansible.builtin.service:
    name: munge
    state: restarted
    daemon_reload: true

- name: Restart slurmctld
  ansible.builtin.systemd:
    name: slurmctld
    state: restarted
    daemon_reload: true

- name: Restart slurmd
  ansible.builtin.systemd:
    name: slurmd
    state: restarted
    daemon_reload: true
