---
# Configure MUNGE authentication for SLURM

- name: Install common packages for Debian/Ubuntu
  ansible.builtin.apt:
    name:
      - munge
      - libmunge-dev
    state: present
  become: true

- name: Create munge key directory
  ansible.builtin.file:
    path: /etc/munge
    state: directory
    mode: '0700'
    owner: munge
    group: munge
  become: true

- name: Check if munge key exists on control node
  ansible.builtin.stat:
    path: /etc/munge/munge.key
  register: munge_key_stat
  become: true
  
- name: Generate munge key on control node
  shell: /usr/bin/mungekey -c -f
  become: true
  when: inventory_hostname in groups['login'] and not munge_key_stat.stat.exists

- name: Fetch munge key from control node
  ansible.builtin.fetch:
    src: /etc/munge/munge.key
    dest: /tmp/munge.key
    flat: yes
  become: true
  when: inventory_hostname in groups['login']

- name: Copy munge key to all nodes
  ansible.builtin.copy:
    src: /tmp/munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0400'
  become: true
  when: inventory_hostname not in groups['control']
  notify:
    - Restart munge

- name: Ensure munge service is enabled and running
  ansible.builtin.service:
    name: munge
    state: started
    enabled: yes
  become: true 