---
# Pyxis

- name: Install pyxis dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - libslurm-dev

- name: Clone pyxis repository
  ansible.builtin.git:
    repo: "https://github.com/NVIDIA/pyxis"
    dest: /opt/pyxis
    version: "v0.20.0" # https://github.com/NVIDIA/pyxis/releases
    depth: 1
    force: true

- name: Compile and install pyxis
  ansible.builtin.make:
    chdir: /opt/pyxis
    target: install

- name: Add pyxis.conf to slurm plugstack directory
  ansible.builtin.lineinfile:
    path: /etc/slurm/plugstack.conf
    line: "required /usr/local/lib/slurm/spank_pyxis.so runtime_path=/tmp/pyxis execute_entrypoint=0 container_scope=global sbatch_support=1"
    state: present
    create: yes
  notify: Restart slurmd
