---

# Slurm dependencies

- name: Install SLURM base packages
  ansible.builtin.package:
    name:
      - slurm-wlm={{ slurm_version_string }}
      - slurm-wlm-basic-plugins={{ slurm_version_string }}
      - mailutils
      - libpmix2
      - libpmix-bin
    update_cache: true
    state: present

# Slurm configuration

- name: Create SLURM configuration directory
  ansible.builtin.file:
    path: /etc/slurm
    state: directory
    mode: '0755'

- name: Create SLURM configuration file
  ansible.builtin.template:
    src: ./templates/etc/slurm/slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    mode: '0644'

- name: Create SLURM state directory
  ansible.builtin.file:
    path: /var/spool/slurmctld
    state: directory
    mode: '0755'
    owner: slurm
    group: slurm

# PMIx configuration

- name: Create custom ld.so.conf file for PMIx
  ansible.builtin.copy:
    dest: /etc/ld.so.conf.d/pmix.conf
    content: /usr/lib/x86_64-linux-gnu
    owner: root
    group: root
    mode: '0644'

- name: Run ldconfig to update shared library cache
  ansible.builtin.command: ldconfig
  changed_when: true

# Control node tasks

- name: Enable and start SLURM controller service
  ansible.builtin.systemd:
    name: slurmctld
    state: started
    enabled: true
    daemon_reload: true
  when: inventory_hostname in groups['login']
  notify: Restart slurmctld

# Compute nodes tasks

- name: Copy GRES configuration file to compute nodes
  ansible.builtin.copy:
    src: etc/slurm/gres.conf
    dest: /etc/slurm/gres.conf
    mode: '0644'
  when: inventory_hostname in groups['compute']

- name: Enable and start SLURM compute node service
  ansible.builtin.systemd:
    name: slurmd
    state: started
    enabled: true
    daemon_reload: true
  when: inventory_hostname in groups['compute']
