---
- name: Install SLURM base packages
  ansible.builtin.package:
    name:
      - slurm-wlm={{ slurm_version_string }}
      - slurm-wlm-basic-plugins={{ slurm_version_string }}
      - mailutils
      - libpmix-dev
    update_cache: true
    state: present
  vars:
    slurm_version_string: "23.11.4-1.2ubuntu5"

- name: Create SLURM configuration directory
  ansible.builtin.file:
    path: /etc/slurm
    state: directory
    mode: '0755'

- name: Create SLURM configuration file
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    mode: '0644'

- name: Create SLURM state directory
  ansible.builtin.file:
    path: /var/spool/slurmctld
    state: directory
    mode: '0755'
    owner: slurm
    group: slurm

# Control Node tasks

- name: Enable and start SLURM controller service
  ansible.builtin.systemd:
    name: slurmctld
    state: started
    enabled: true
    daemon_reload: true
  when: inventory_hostname in groups['login']
  notify: Restart slurmctld

# Compute node tasks

- name: Copy GRES configuration file to compute nodes
  ansible.builtin.copy:
    src: gres.conf
    dest: /etc/slurm/gres.conf
    mode: '0644'
  when: inventory_hostname in groups['compute']

- name: Enable and start SLURM compute node service
  ansible.builtin.systemd:
    name: slurmd
    state: started
    enabled: true
    daemon_reload: true
  when: inventory_hostname in groups['compute']
