---
- name: Configure the cluster
  hosts: all
  roles:
    - role: common  # Common tasks
    - role: storage # Storage tasks
    #- role: gpu     # Nvidia drivers need to be installed before slurm
    #- role: slurm   # SLURM tasks
