---
- name: Configure the cluster
  hosts: all
  roles:
    - role: common  # Common tasks
    - role: storage # Shared persistent storage
    - role: gpu     # Nvidia drivers need to be installed before slurm
    - role: slurm   # Install SLURM components
